### ISSUE TITLE
Single quotes being parsed incorrectly for syntax highlighting. 

### ISSUE THREAD

**Issue by radfahrer** [atuttle/atom-language-cfml#10]
For example: 

```cfml
<h6><span>Can't open parts diagram?</span></h6>
```

breaks after "Can"

**Comment by shutterassault** [comment]
I've had the same problem.  Glad to see I wasn't the only one.

**Comment by seancoyne** [comment]
I've tracked this down to the cfscript-files section of the grammar ([#L504](https://github.com/atuttle/atom-language-cfml/blob/master/grammars/coldfusion.cson#L504)).  

Perhaps @dajester2013 can take a look since he was the one who added this section.  I can't seem to determine what is going on.  

It seems to be treating regular *.cfm files as cfscript files which is causing the parsing errors.  I have a file with just the word "interface" init and it is highlighting it as though I was creating a cfscript interface CFC.  I wonder if there is a way to restrict those rules to only CFC files and only those that are script based CFCs.

**Comment by jfmontanaro** [comment]
I know very little about Atom language definitions, but I took a peek through the files in the package and came across grammars/coldfusion #L287:

`# when nothing tag-related matches, assume cfscript. this fixes alot of problems when dealing with files that either start with import, component or some form of comment.`

Could this functionality be triggering unnecessarily?

**Comment by TheFlyingFish** [comment]
After further tinkering, I found a workaround.  It's ugly, but it more-or-less works, at least for my usage.  I discovered that commenting out lines 287-289 in grammars/coldfusion.cson would get rid of the problem in CFML templates.  However, as might be expected, it also broke syntax highlighting entirely in .cfc files starting with `component` and the like.  So my solution was to copy the package and edit the `'fileTypes'` block at the top of the file so that one package (the one with lines 287-289 removed) only looked at .cfm and .cfml files, while the other package (with those lines left in) only looked at .cfc files.  I also edited the `name` attribute in each file so they were distinguishable.

Obviously this is an ugly workaround, but it works for my purposes.  Hopefully someone who knows more than I do about language packages can provide a real fix.

**Comment by jfmontanaro** [comment]
Whoops, posted with the wrong account.

After further tinkering, I found a workaround.  It's ugly, but it more-or-less works, at least for my usage.  I discovered that commenting out lines 287-289 in grammars/coldfusion.cson would get rid of the problem in CFML templates.  However, as might be expected, it also broke syntax highlighting entirely in .cfc files starting with `component` and the like.  So my solution was to copy the package and edit the `'fileTypes'` block at the top of the file so that one package (the one with lines 287-289 removed) only looked at .cfm and .cfml files, while the other package (with those lines left in) only looked at .cfc files.  I also edited the `name` attribute in each file so they were distinguishable.

Obviously this is an ugly workaround, but it mostly works for my purposes, since I don't use tags in .cfc files very much.  Hopefully someone who knows more than I do about language packages can provide a real fix.

**Comment by David-Polehonski** [comment]
I found the cfscipt catch all was causing problems with parsing plain text content so have turned it of on my dev branch of the project until I find a better way to trigger it.

**Comment by David-Polehonski** [comment]
Is this still an issue or can we close it?

**Comment by ArtskydJ** [comment]
I tested this `<h6><span>Can't open parts diagram?</span></h6>` in 0.8.6, and I couldn't replicate the issue.
